### ISSUE TITLE
IDE management

### ISSUE THREAD

**Issue by fabjanvucina** [daytonaio/enterprise-docs#116]
Daytona admins can manage which IDEs can be used for opening workspaces.

![image](https://github.com/user-attachments/assets/e6e55a89-167e-4c6d-aa22-22e6e36739fc)

**Comment by stefanicjuraj** [comment]
I have the documentation changes ready for this - waiting for the administration section to be merged so I can add a separate _settings_ page that will cover the IDE management.

<img width="789" alt="image" src="https://github.com/user-attachments/assets/82df4dec-b809-40f4-b1de-43e4acc8dab0">
