### ISSUE TITLE
Identity providers management

### ISSUE THREAD

**Issue by fabjanvucina** [daytonaio/enterprise-docs#123]
This is a new admin feature. Admins now have the ability to configure supported identity providers from the dashboard. Identity providers can be added, edited or deleted.

Specific identity providers have different configuration options.

**Comment by stefanicjuraj** [comment]
Hi, where is this feature available so I can try it out?

I have access to the admin staging review instance that has the following options available in the sidebar:

<img width="225" alt="image" src="https://github.com/user-attachments/assets/aacd22c0-1011-4dd9-a7cc-6e9cd682d13f">

**Comment by ivan-burazin** [comment]
@fabjanvucina add @stefanicjuraj as admin to demo

**Comment by fabjanvucina** [comment]
@stefanicjuraj It will be merged sometime today probably. We will add you as an admin on the demo deployment and then you will be able to see it.

**Comment by fabjanvucina** [comment]
@stefanicjuraj You're added as an admin on the demo deployment.

**Comment by ivan-burazin** [comment]
Still no IdP on EU

**Comment by fabjanvucina** [comment]
Not merged + release yet.  Waiting on some final config cleanup. Will let you know when it's available.
