### ISSUE TITLE
Incorrect content under "Workspaces"

### ISSUE THREAD

**Issue by marko-baric-ca** [daytonaio/enterprise-docs#143]
-- Create Workspace - Step 3 (Select the dev container configuration file for your Workspace.)

This does not exist in the real Dashboard when creating new Workspace.

**Comment by fabjanvucina** [comment]
@marko-baric-ca If you select a Git repository which includes at least one `devcontainer.json` file, we will display the dropdown where the user can select the preferred configuration file for their Workspace.

<img width="1025" alt="image" src="https://github.com/user-attachments/assets/37cc67a5-5c20-46d4-afc6-d1402a0d903e">

**Comment by marko-baric-ca** [comment]
In that case, we need to change the text in the docs to say "If Git repository includes at least one devcontainer.json, drop-down is displayed...."

**Comment by fabjanvucina** [comment]
> If the selected Git repository includes a devcontainer.json configuration file, you will be prompted to select the configuration file for your Workspace.

The docs already include a paragraph about this. If you think it's not clear enough, we can reopen the issue 👍

**Comment by marko-baric-ca** [comment]
Ok, close it
