### ISSUE TITLE
RBAC

### ISSUE THREAD

**Issue by fabjanvucina** [daytonaio/enterprise-docs#145]
We've introduced role-based access control to the Enterprise product. 

The docs should cover the newly updated users panel in the admin dashboard.

At the moment, the following roles exist:
- Owner
- User Admin
- Member

**Owner**
- Assign/unassign user roles
- Enable/disable user
- Delete user
- Manage workspace classes
- Manage identity providers
- Manage global settings
- Manage license

**User Admin**
- Enable/disable user
- Delete user

**Member**
- Everybody is a member. This is a default role for all users.

The roles and their authorized actions will be updated as new features are released. 

<img width="1274" alt="image" src="https://github.com/user-attachments/assets/c51863ad-ad4a-4d6f-8529-0c1f729181d6">

**Comment by ivan-burazin** [comment]
@stefanicjuraj
