### ISSUE TITLE
Team quotas

### ISSUE THREAD

**Issue by fabjanvucina** [daytonaio/enterprise-docs#150]
Quotas define resource limits assigned to users within a team. These quotas can now be managed inside a new panel in the admin dashboard.

At the moment, quotas can define:
- Workspace credits
- Idle timeout for stopping inactive workspaces
- Limit for simultaneously active workspace
- Limit for number of pinned workspaces

Each of these limits are optional. If left unset, usage of the corresponding resource will not be limited.

The first highlighted quota in the list represents the Default quota. This quota is applied to all new Personal teams by default.

<img width="1033" alt="image" src="https://github.com/user-attachments/assets/8299bce2-035b-4170-b3da-10e00fdd04cd">

The admin can decide whether this Default quota wil also be applied to **all** new teams.

<img width="999" alt="image" src="https://github.com/user-attachments/assets/815e6db8-dfcc-44bd-9d09-0a4ca5ecfa12">

In the teams panel, admins can apply or revoke team quotas.

<img width="906" alt="image" src="https://github.com/user-attachments/assets/1f6db676-aa19-4c54-a674-bd28a3e11a91">

<img width="905" alt="image" src="https://github.com/user-attachments/assets/88715bab-f54b-4d8d-b351-3e3d26f15b00">

**Comment by ivan-burazin** [comment]
@stefanicjuraj

**Comment by fabjanvucina** [comment]
Reminer: look for all mentions of subscriptions and replace it with the new terminology
