### ISSUE TITLE
Cursor IDE

### ISSUE THREAD

**Issue by fabjanvucina** [daytonaio/enterprise-docs#152]
We've added support for the [Cursor IDE](https://www.cursor.com/). It needs to be added to the list of supported IDEs.

Note:
- If your browser window is open in full screen, you will not immediately see the prompt for opening the Cursor IDE. This is something that needs to conveyed to the user reading the docs. Feel free to think of a clear disclaimer for the docs page.

Non-fullscreen:

https://github.com/user-attachments/assets/b361d996-9be3-4b92-bbea-805f37bf4dfb

Fullscreen:

https://github.com/user-attachments/assets/334633ca-ff87-4582-8785-442b50f9c9bd

**Comment by ivan-burazin** [comment]
@stefanicjuraj
