### ISSUE TITLE
Page about "how to customize workspace with Dev Container files"

### ISSUE THREAD

**Issue by marko-baric-ca** [daytonaio/enterprise-docs#161]
We need a docs page about devcontainer.json that explains to user how to customize the setup of their containers. You can copy and modify the blog post about that topic, Toma Puljak wrote on for Daytona blog. Clean the content from there to make it more docs-like with instructions to users on how to set up dev containers in their repos. and we're good.

**Comment by ivan-burazin** [comment]
@marko-baric-ca agreed. 
@stefanicjuraj this is the builder section, although we have it in OSS i think we need a deeper explanation on OSS and ad the section here in EE
