### ISSUE TITLE
Add About page specifically for Codeanywhere use-case

### ISSUE THREAD

**Issue by marko-baric-ca** [daytonaio/enterprise-docs#163]
We need a copy of About docs page, but focused more on what Codeanywhere is and what users can do with it, high-level use cases.

**Comment by ivan-burazin** [comment]
@marko-baric-ca there is no about in docs.

**Comment by marko-baric-ca** [comment]
@ivan-burazin Not true, you have it already: https://github.com/daytonaio/enterprise-docs/blob/main/src/content/docs/about/what-is-daytona.mdx

I need the equivalent for Codeanywhere. So either we can add it here, or we will do it manually in CA.

**Comment by ivan-burazin** [comment]
@marko-baric-ca we need to first edit About https://github.com/daytonaio/enterprise-docs/issues/165

cc @stefanicjuraj
