### ISSUE TITLE
Update Teams doc

### ISSUE THREAD

**Issue by fabjanvucina** [daytonaio/enterprise-docs#29]
I reviewed the content in the Teams section of the documentation. I think we need to add the following things:

1. Add steps for inviting members via email

2. Add info for importing in bulk via CSV file (use the instructions available in the dashboard)
<img width="967" alt="image" src="https://github.com/daytonaio/docs/assets/65237084/82d8a20c-e141-497b-8768-71606b9c7c57">

3. In the managing members section, more info should be added regarding the change role/transfer ownership action

4. We are missing a section which explains the differences between different team roles

**Comment by zmzlois** [comment]
Hey @fabjanvucina there is a PR 
https://github.com/daytonaio/docs/pull/25 
includes import via CSV
pushing updates for issues mention above.

**Comment by zmzlois** [comment]
@fabjanvucina I am attaching several csv file I was using to import team members and it has below errors, don't think the csv format is wrong? 

1. This is the error occured with sheet 1. 
 One of the email was being malformatted as header,  it shown sheet title and one of the email  exists in the team
[email template - Sheet1.csv](https://github.com/daytonaio/docs/files/14010422/email.template.-.Sheet1.csv)

![Screenshot 2024-01-22 at 13 01 08](https://github.com/daytonaio/docs/assets/79988376/ad8b737a-f0c0-4d98-8d82-a88c027ed53c)

2. This is the error occured with sheet2. only two email, one of the email is already in the team
[email template - Sheet2.csv](https://github.com/daytonaio/docs/files/14010466/email.template.-.Sheet2.csv)
![Screenshot 2024-01-22 at 13 11 00](https://github.com/daytonaio/docs/assets/79988376/2437d096-c4f5-4d1e-a60d-8cd5a2f50cca)

3. This is the error occured with sheet3. one success. two of them are imaginary email don't exit. none of them are in the time. I don't see how the email was malformatted
[email template - Sheet3.csv](https://github.com/daytonaio/docs/files/14010498/email.template.-.Sheet3.csv)
![Screenshot 2024-01-22 at 13 15 15](https://github.com/daytonaio/docs/assets/79988376/363624ce-5688-41ab-acf1-b55033da818a)

**Comment by fabjanvucina** [comment]
> Hey @fabjanvucina there is a PR #25 includes import via CSV pushing updates for issues mention above.

My comments are regarding the content that has been recently pushed to the main branch.
I would suggest that we open a new pull request from this issue and add the required additional content there.

**Comment by fabjanvucina** [comment]
Re: importing from a CSV file

Thank you for noticing a potential bug, but we should not discuss it here as it is not within the scope of this docs issue.

**Comment by ivan-burazin** [comment]
@zmzlois this is for the other version. thanks!
