### ISSUE TITLE
Add Admin section

### ISSUE THREAD

**Issue by zzorica** [daytonaio/enterprise-docs#90]
Need to add admin section to docs as we now have admin dashboard with:

* licence
* workspace-classes
* users

![image](https://github.com/user-attachments/assets/aceb25cb-351c-4e79-8185-1f04bdbe3f6c)

**Comment by stefanicjuraj** [comment]
Listing all the pull requests with sections that are being added (or have been added) to track progress:
- License - https://github.com/daytonaio/enterprise-docs/pull/137 
- Users - https://github.com/daytonaio/enterprise-docs/pull/110 
- Workspace classes - https://github.com/daytonaio/enterprise-docs/pull/138 
- Settings - https://github.com/daytonaio/enterprise-docs/pull/148 

@ivan-burazin
